const STRATAGEMS = {
    1: {
        name: "machine_gun",
        short_name: "Machine Gun",
        long_name: "MG-43 Machine Gun",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    2: {
        name: "anti_materiel_rifle",
        short_name: "Anti-Materiel Rifle",
        long_name: "APW-1 Anti-Materiel Rifle",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    3: {
        name: "stalwart",
        short_name: "Stalwart",
        long_name: "M-105 Stalwart",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    4: {
        name: "expendable_anti_tank",
        short_name: "Expendable Anti-Tank",
        long_name: "EAT-17 Expendable Anti-Tank",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: true,
    },
    5: {
        name: "recoilless_rifle",
        short_name: "Recoilless Rifle",
        long_name: "GR-8 Recoilless Rifle",
        station: 1,
        active: true,
        backpack: true,
        support_weapon: true,
        heavy_ordinance: true,
    },
    6: {
        name: "flamethrower",
        short_name: "Flamethrower",
        long_name: "FLAM-40 Flamethrower",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    7: {
        name: "autocannon",
        short_name: "Autocannon",
        long_name: "AC-8 Autocannon",
        station: 1,
        active: true,
        backpack: true,
        support_weapon: true,
        heavy_ordinance: false,
    },
    8: {
        name: "heavy_machine_gun",
        short_name: "Heavy Machine Gun",
        long_name: "MG-206 Heavy Machine Gun",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    9: {
        name: "railgun",
        short_name: "Railgun",
        long_name: "RS-422 Railgun",
        station: 1,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    10: {
        name: "spear",
        short_name: "SPEAR",
        long_name: "FAF-154 SPEAR Launcher",
        station: 1,
        active: true,
        backpack: true,
        support_weapon: true,
        heavy_ordinance: false,
    },
    11: {
        name: "gatling_barrage",
        short_name: "Gatling Barrage",
        long_name: "Orbital Gatling Barrage",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    12: {
        name: "airburst_strike",
        short_name: "Airburst Strike",
        long_name: "Orbital Airburst Strike",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    13: {
        name: "120_he_barrage",
        short_name: "120MM HE Barrage",
        long_name: "Orbital 120MM HE Barrage",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    14: {
        name: "380_he_barrage",
        short_name: "380MM HE Barrage",
        long_name: "Orbital 380MM HE Barrage",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    15: {
        name: "walking_barrage",
        short_name: "Walking Barrage",
        long_name: "Orbital Walking Barrage",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    16: {
        name: "orbital_laser",
        short_name: "Orbital Laser",
        long_name: "Orbital Laser",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    17: {
        name: "railcannon_strike",
        short_name: "Railcannon Strike",
        long_name: "Orbital Railcannon Strike",
        station: 2,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    18: {
        name: "strafing_run",
        short_name: "Eagle Strafing Run",
        long_name: "Eagle Strafing Run",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    19: {
        name: "airstrike",
        short_name: "Eagle Airstrike",
        long_name: "Eagle Airstrike",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    20: {
        name: "cluster_bomb",
        short_name: "Eagle Cluster Bomb",
        long_name: "Eagle Cluster Bomb",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    21: {
        name: "napalm_airstrike",
        short_name: "Eagle Napalm Airstrike",
        long_name: "Eagle Napalm Airstrike",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    22: {
        name: "jump_pack",
        short_name: "Jump Pack",
        long_name: "LIFT-850 Jump Pack",
        station: 3,
        active: true,
        backpack: true,
        support_weapon: false,
        heavy_ordinance: false,
    },
    23: {
        name: "smoke_strike",
        short_name: "Eagle Smoke Strike",
        long_name: "Eagle Smoke Strike",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    24: {
        name: "rocket_pods",
        short_name: "Eagle Rocket Pods",
        long_name: "Eagle 110MM Rocket Pods",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    25: {
        name: "500_kg_bomb",
        short_name: "Eagle 500KG Bomb",
        long_name: "Eagle 500KG Bomb",
        station: 3,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    26: {
        name: "precision_strike",
        short_name: "Precision Strike",
        long_name: "Orbital Precision Strike",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    27: {
        name: "gas_strike",
        short_name: "Orbital Gas Strike",
        long_name: "Orbital Gas Strike",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    28: {
        name: "ems_strike",
        short_name: "Orbital EMS Strike",
        long_name: "Orbital EMS Strike",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    29: {
        name: "orbital_smoke_strike",
        short_name: "Orbital Smoke Strike",
        long_name: "Orbital Smoke Strike",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    30: {
        name: "hmg_emplacement",
        short_name: "HMG Emplacement",
        long_name: "E/MG-101 HMG Emplacement",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    31: {
        name: "shield_generator_relay",
        short_name: "Shield Generator Relay",
        long_name: "FX-12 Shield Generator Relay",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    32: {
        name: "tesla_tower",
        short_name: "Tesla Tower",
        long_name: "A/ARC-3 Tesla Tower",
        station: 4,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    33: {
        name: "anti_personnel_minefield",
        short_name: "Anti-Personnel Minefield",
        long_name: "MD-6 Anti-Personnel Minefield",
        station: 5,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    34: {
        name: "supply_pack",
        short_name: "Supply Pack",
        long_name: "B-1 Supply Pack",
        station: 5,
        active: true,
        backpack: true,
        support_weapon: false,
        heavy_ordinance: false,
    },
    35: {
        name: "grenade_launcher",
        short_name: "Grenade Launcher",
        long_name: "GL-21 Grenade Launcher",
        station: 5,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    36: {
        name: "laser_cannon",
        short_name: "Laser Cannon",
        long_name: "LAS-98 Laser Cannon",
        station: 5,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    37: {
        name: "incendiary_mines",
        short_name: "Incendiary Mines",
        long_name: "MD-14 Incendiary Mines",
        station: 5,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    38: {
        name: "guard_dog_rover",
        short_name: "'Guard Dog' Rover",
        long_name: "AX/LAS-5 'Guard Dog' Rover",
        station: 5,
        active: true,
        backpack: true,
        support_weapon: false,
        heavy_ordinance: false,
    },
    39: {
        name: "ballistic_shield",
        short_name: "Ballistic Shield Backpack",
        long_name: "SH-20 Ballistic Shield Backpack",
        station: 5,
        active: true,
        backpack: true,
        support_weapon: false,
        heavy_ordinance: false,
    },
    40: {
        name: "arc_thrower",
        short_name: "Arc Thrower",
        long_name: "ARC-3 Arc Thrower",
        station: 5,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: false,
    },
    41: {
        name: "quasar_cannon",
        short_name: "Quasar Cannon",
        long_name: "LAS-99 Quasar Cannon",
        station: 5,
        active: true,
        backpack: false,
        support_weapon: true,
        heavy_ordinance: true,
    },
    42: {
        name: "shield_generator_pack",
        short_name: "Shield Generator Pack",
        long_name: "SH-32 Shield Generator Pack",
        station: 5,
        active: true,
        backpack: true,
        support_weapon: false,
        heavy_ordinance: false,
    },
    43: {
        name: "machine_gun_sentry",
        short_name: "Machine Gun Sentry",
        long_name: "A/MG-43 Machine Gun Sentry",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    44: {
        name: "gatling_sentry",
        short_name: "Gatling Sentry",
        long_name: "A/G-16 Gatling Sentry",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    45: {
        name: "mortar_sentry",
        short_name: "Mortar Sentry",
        long_name: "A/M-12 Mortar Sentry",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    46: {
        name: "guard_dog",
        short_name: "'Guard Dog'",
        long_name: "AX/AR-23 'Guard Dog'",
        station: 6,
        active: true,
        backpack: true,
        support_weapon: false,
        heavy_ordinance: false,
    },
    47: {
        name: "autocannon_sentry",
        short_name: "Autocannon Sentry",
        long_name: "A/AC-8 Autocannon Sentry",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    48: {
        name: "rocket_sentry",
        short_name: "Rocket Sentry",
        long_name: "A/MLS-4X Rocket Sentry",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
    49: {
        name: "ems_mortar_sentry",
        short_name: "EMS Mortar Sentry",
        long_name: "A/M-23 EMS Mortar Sentry",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: false,
    },
    50: {
        name: "patriot_exosuit",
        short_name: "Patriot Exosuit",
        long_name: "EXO-45 Patriot Exosuit",
        station: 6,
        active: true,
        backpack: false,
        support_weapon: false,
        heavy_ordinance: true,
    },
};

export default STRATAGEMS;