const STRATAGEMS = {
    // ========================================
    // PATRIOTIC ADMINISTRATION CENTER
    // ========================================
    machine_gun: {
        short_name: "Machine Gun",
        long_name: "MG-43 Machine Gun",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Machine Gun.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    anti_materiel_rifle: {
        short_name: "Anti-Materiel Rifle",
        long_name: "APW-1 Anti-Materiel Rifle",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Anti-Materiel Rifle.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    stalwart: {
        short_name: "Stalwart",
        long_name: "M-105 Stalwart",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Stalwart.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    expendable_anti_tank: {
        short_name: "Expendable Anti-Tank",
        long_name: "EAT-17 Expendable Anti-Tank",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Expendable Anti-Tank.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    recoilless_rifle: {
        short_name: "Recoilless Rifle",
        long_name: "GR-8 Recoilless Rifle",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Recoilless Rifle.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: true,
    },
    flamethrower: {
        short_name: "Flamethrower",
        long_name: "FLAM-40 Flamethrower",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Flamethrower.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    autocannon: {
        short_name: "Autocannon",
        long_name: "AC-8 Autocannon",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Autocannon.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: true,
    },
    heavy_machine_gun: {
        short_name: "Heavy Machine Gun",
        long_name: "MG-206 Heavy Machine Gun",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Heavy Machine Gun.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    airburst_rocket_launcher: {
        short_name: "Airburst Rocket Launcher",
        long_name: "RL-77 Airburst Rocket Launcher",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Airburst Rocket Launcher.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    railgun: {
        short_name: "Railgun",
        long_name: "RS-422 Railgun",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Railgun.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    spear: {
        short_name: "SPEAR",
        long_name: "FAF-154 SPEAR Launcher",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Spear.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: true,
    },
    commando: {
        short_name: "Commando",
        long_name: "Commando",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/Commando.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    sta_x3_wasp_launcher: {
        short_name: "StA-X3 W.A.S.P. Launcher",
        long_name: "StA-X3 W.A.S.P. Launcher",
        station: "patriotic_administration_center",
        icon: "Patriotic Administration Center/StA-X3 W.A.S.P. Launcher.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },

    // ========================================
    // ORBITAL CANNONS
    // ========================================
    gatling_barrage: {
        short_name: "Gatling Barrage",
        long_name: "Orbital Gatling Barrage",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital Gatling Barrage.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    airburst_strike: {
        short_name: "Airburst Strike",
        long_name: "Orbital Airburst Strike",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital Airburst Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    orbital_120_he_barrage: {
        short_name: "120MM HE Barrage",
        long_name: "Orbital 120MM HE Barrage",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital 120MM HE Barrage.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    orbital_380_he_barrage: {
        short_name: "380MM HE Barrage",
        long_name: "Orbital 380MM HE Barrage",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital 380MM HE Barrage.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    walking_barrage: {
        short_name: "Walking Barrage",
        long_name: "Orbital Walking Barrage",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital Walking Barrage.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    orbital_laser: {
        short_name: "Orbital Laser",
        long_name: "Orbital Laser",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital Laser.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    railcannon_strike: {
        short_name: "Railcannon Strike",
        long_name: "Orbital Railcannon Strike",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital Railcannon Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    orbital_napalm_barrage: {
        short_name: "Orbital Napalm Barrage",
        long_name: "Orbital Napalm Barrage",
        station: "orbital_cannons",
        icon: "Orbital Cannons/Orbital Napalm Barrage.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },

    // ========================================
    // HANGAR
    // ========================================
    strafing_run: {
        short_name: "Eagle Strafing Run",
        long_name: "Eagle Strafing Run",
        station: "hangar",
        icon: "Hangar/Eagle Strafing Run.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    airstrike: {
        short_name: "Eagle Airstrike",
        long_name: "Eagle Airstrike",
        station: "hangar",
        icon: "Hangar/Eagle Airstrike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    cluster_bomb: {
        short_name: "Eagle Cluster Bomb",
        long_name: "Eagle Cluster Bomb",
        station: "hangar",
        icon: "Hangar/Eagle Cluster Bomb.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    napalm_airstrike: {
        short_name: "Eagle Napalm Airstrike",
        long_name: "Eagle Napalm Airstrike",
        station: "hangar",
        icon: "Hangar/Eagle Napalm Airstrike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    jump_pack: {
        short_name: "Jump Pack",
        long_name: "LIFT-850 Jump Pack",
        station: "hangar",
        icon: "Hangar/Jump Pack.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: false,
    },
    smoke_strike: {
        short_name: "Eagle Smoke Strike",
        long_name: "Eagle Smoke Strike",
        station: "hangar",
        icon: "Hangar/Eagle Smoke Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    rocket_pods: {
        short_name: "Eagle Rocket Pods",
        long_name: "Eagle 110MM Rocket Pods",
        station: "hangar",
        icon: "Hangar/Eagle 110MM Rocket Pods.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    eagle_500kg_bomb: {
        short_name: "Eagle 500KG Bomb",
        long_name: "Eagle 500KG Bomb",
        station: "hangar",
        icon: "Hangar/Eagle 500KG Bomb.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    fast_recon_vehicle: {
        short_name: "Fast Recon Vehicle",
        long_name: "Fast Recon Vehicle",
        station: "hangar",
        icon: "Hangar/Fast Recon Vehicle.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },

    // ========================================
    // BRIDGE
    // ========================================
    precision_strike: {
        short_name: "Precision Strike",
        long_name: "Orbital Precision Strike",
        station: "bridge",
        icon: "Bridge/Orbital Precision Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    gas_strike: {
        short_name: "Orbital Gas Strike",
        long_name: "Orbital Gas Strike",
        station: "bridge",
        icon: "Bridge/Orbital Gas Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    ems_strike: {
        short_name: "Orbital EMS Strike",
        long_name: "Orbital EMS Strike",
        station: "bridge",
        icon: "Bridge/Orbital EMS Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    orbital_smoke_strike: {
        short_name: "Orbital Smoke Strike",
        long_name: "Orbital Smoke Strike",
        station: "bridge",
        icon: "Bridge/Orbital Smoke Strike.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    hmg_emplacement: {
        short_name: "HMG Emplacement",
        long_name: "E/MG-101 HMG Emplacement",
        station: "bridge",
        icon: "Bridge/HMG Emplacement.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    shield_generator_relay: {
        short_name: "Shield Generator Relay",
        long_name: "FX-12 Shield Generator Relay",
        station: "bridge",
        icon: "Bridge/Shield Generator Relay.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    tesla_tower: {
        short_name: "Tesla Tower",
        long_name: "A/ARC-3 Tesla Tower",
        station: "bridge",
        icon: "Bridge/Tesla Tower.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    grenadier_battlement: {
        short_name: "Grenadier Battlement",
        long_name: "Grenadier Battlement",
        station: "bridge",
        icon: "Bridge/Grenadier Battlement.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },

    // ========================================
    // ENGINEERING BAY
    // ========================================
    anti_personnel_minefield: {
        short_name: "Anti-Personnel Minefield",
        long_name: "MD-6 Anti-Personnel Minefield",
        station: "engineering_bay",
        icon: "Engineering Bay/Anti-Personnel Minefield.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    supply_pack: {
        short_name: "Supply Pack",
        long_name: "B-1 Supply Pack",
        station: "engineering_bay",
        icon: "Engineering Bay/Supply Pack.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: false,
    },
    grenade_launcher: {
        short_name: "Grenade Launcher",
        long_name: "GL-21 Grenade Launcher",
        station: "engineering_bay",
        icon: "Engineering Bay/Grenade Launcher.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    laser_cannon: {
        short_name: "Laser Cannon",
        long_name: "LAS-98 Laser Cannon",
        station: "engineering_bay",
        icon: "Engineering Bay/Laser Cannon.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    incendiary_mines: {
        short_name: "Incendiary Mines",
        long_name: "MD-14 Incendiary Mines",
        station: "engineering_bay",
        icon: "Engineering Bay/Incendiary Mines.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    guard_dog_rover: {
        short_name: "'Guard Dog' Rover",
        long_name: "AX/LAS-5 'Guard Dog' Rover",
        station: "engineering_bay",
        icon: "Engineering Bay/Guard Dog Rover.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: false,
    },
    ballistic_shield: {
        short_name: "Ballistic Shield Backpack",
        long_name: "SH-20 Ballistic Shield Backpack",
        station: "engineering_bay",
        icon: "Engineering Bay/Ballistic Shield Backpack.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: false,
    },
    arc_thrower: {
        short_name: "Arc Thrower",
        long_name: "ARC-3 Arc Thrower",
        station: "engineering_bay",
        icon: "Engineering Bay/Arc Thrower.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    quasar_cannon: {
        short_name: "Quasar Cannon",
        long_name: "LAS-99 Quasar Cannon",
        station: "engineering_bay",
        icon: "Engineering Bay/Quasar Cannon.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: true,
    },
    shield_generator_pack: {
        short_name: "Shield Generator Pack",
        long_name: "SH-32 Shield Generator Pack",
        station: "engineering_bay",
        icon: "Engineering Bay/Shield Generator Pack.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: false,
    },
    anti_tank_mines: {
        short_name: "Anti-Tank Mines",
        long_name: "Anti-Tank Mines",
        station: "engineering_bay",
        icon: "Engineering Bay/Anti-Tank Mines.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    gas_mine: {
        short_name: "Gas Mine",
        long_name: "Gas Mine",
        station: "engineering_bay",
        icon: "Engineering Bay/Gas Mine.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },

    // ========================================
    // ROBOTICS WORKSHOP
    // ========================================
    machine_gun_sentry: {
        short_name: "Machine Gun Sentry",
        long_name: "A/MG-43 Machine Gun Sentry",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Machine Gun Sentry.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    gatling_sentry: {
        short_name: "Gatling Sentry",
        long_name: "A/G-16 Gatling Sentry",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Gatling Sentry.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    mortar_sentry: {
        short_name: "Mortar Sentry",
        long_name: "A/M-12 Mortar Sentry",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Mortar Sentry.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    guard_dog: {
        short_name: "'Guard Dog'",
        long_name: "AX/AR-23 'Guard Dog'",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Guard Dog.svg",
        warbond: null,
        active: true,
        backpack: true,
        support_weapon: false,
    },
    autocannon_sentry: {
        short_name: "Autocannon Sentry",
        long_name: "A/AC-8 Autocannon Sentry",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Autocannon Sentry.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    rocket_sentry: {
        short_name: "Rocket Sentry",
        long_name: "A/MLS-4X Rocket Sentry",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Rocket Sentry.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    ems_mortar_sentry: {
        short_name: "EMS Mortar Sentry",
        long_name: "A/M-23 EMS Mortar Sentry",
        station: "robotics_workshop",
        icon: "Robotics Workshop/EMS Mortar Sentry.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    patriot_exosuit: {
        short_name: "Patriot Exosuit",
        long_name: "EXO-45 Patriot Exosuit",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Patriot Exosuit.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },
    emancipator_exosuit: {
        short_name: "Emancipator Exosuit",
        long_name: "Emancipator Exosuit",
        station: "robotics_workshop",
        icon: "Robotics Workshop/Emancipator Exosuit.svg",
        warbond: null,
        active: true,
        backpack: false,
        support_weapon: false,
    },

    // ========================================
    // PREMIUM WARBONDS
    // ========================================

    // --- Borderline Justice ---
    hover_pack: {
        short_name: "Hover Pack",
        long_name: "Hover Pack",
        station: null,
        icon: "Borderline Justice/Hover Pack.svg",
        warbond: "borderline_justice",
        active: false,
        backpack: true,
        support_weapon: false,
    },

    // --- Chemical Agents ---
    guard_dog_breath: {
        short_name: "Guard Dog Breath",
        long_name: "Guard Dog Breath",
        station: null,
        icon: "Chemical Agents/Guard Dog Breath.svg",
        warbond: "chemical_agents",
        active: false,
        backpack: true,
        support_weapon: false,
    },
    sterilizer: {
        short_name: "Sterilizer",
        long_name: "Sterilizer",
        station: null,
        icon: "Chemical Agents/Sterilizer.svg",
        warbond: "chemical_agents",
        active: false,
        backpack: false,
        support_weapon: true,
    },

    // --- Control Group ---
    epoch: {
        short_name: "Epoch",
        long_name: "Epoch",
        station: null,
        icon: "Control Group/Epoch.svg",
        warbond: "control_group",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    laser_sentry: {
        short_name: "Laser Sentry",
        long_name: "Laser Sentry",
        station: null,
        icon: "Control Group/Laser Sentry.svg",
        warbond: "control_group",
        active: false,
        backpack: false,
        support_weapon: false,
    },
    warp_pack: {
        short_name: "Warp Pack",
        long_name: "Warp Pack",
        station: null,
        icon: "Control Group/Warp Pack.svg",
        warbond: "control_group",
        active: false,
        backpack: true,
        support_weapon: false,
    },

    // --- Dust Devils ---
    expendable_napalm: {
        short_name: "Expendable Napalm",
        long_name: "Expendable Napalm",
        station: null,
        icon: "Dust Devils/Expendable Napalm.svg",
        warbond: "dust_devils",
        active: false,
        backpack: false,
        support_weapon: false,
    },
    solo_silo: {
        short_name: "Solo Silo",
        long_name: "Solo Silo",
        station: null,
        icon: "Dust Devils/Solo Silo.svg",
        warbond: "dust_devils",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    speargun: {
        short_name: "Speargun",
        long_name: "Speargun",
        station: null,
        icon: "Dust Devils/Speargun.svg",
        warbond: "dust_devils",
        active: false,
        backpack: false,
        support_weapon: true,
    },

    // --- Entrenched Division ---
    cremator: {
        short_name: "Cremator",
        long_name: "Cremator",
        station: null,
        icon: "Entrenched Division/Cremator.svg",
        warbond: "entrenched_division",
        active: false,
        backpack: true,
        support_weapon: true,
    },
    gas_mortar_sentry: {
        short_name: "Gas Mortar Sentry",
        long_name: "Gas Mortar Sentry",
        station: null,
        icon: "Entrenched Division/Gas Mortar Sentry.svg",
        warbond: "entrenched_division",
        active: false,
        backpack: false,
        support_weapon: false,
    },

    // --- Exo Experts ---
    breakthrough_exosuit: {
        short_name: "Breakthrough Exosuit",
        long_name: "Breakthrough Exosuit",
        station: null,
        icon: "Exo Experts/Breakthrough Exosuit.svg",
        warbond: "exo_experts",
        active: false,
        backpack: false,
        support_weapon: false,
    },
    bullet_storm: {
        short_name: "Bullet Storm",
        long_name: "Bullet Storm",
        station: null,
        icon: "Exo Experts/Bullet Storm.svg",
        warbond: "exo_experts",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    lumberer_exosuit: {
        short_name: "Lumberer Exosuit",
        long_name: "Lumberer Exosuit",
        station: null,
        icon: "Exo Experts/Lumberer Exosuit.svg",
        warbond: "exo_experts",
        active: false,
        backpack: false,
        support_weapon: false,
    },

    // --- Force of Law ---
    gl_52_de_escalator: {
        short_name: "GL-52 De-Escalator",
        long_name: "GL-52 De-Escalator",
        station: null,
        icon: "Force of Law/GL-52 De-Escalator.svg",
        warbond: "force_of_law",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    guard_dog_k9: {
        short_name: "Guard Dog K-9",
        long_name: "Guard Dog K-9",
        station: null,
        icon: "Force of Law/Guard Dog K-9.svg",
        warbond: "force_of_law",
        active: false,
        backpack: true,
        support_weapon: false,
    },

    // --- Masters of Ceremony ---
    one_true_flag: {
        short_name: "One True Flag",
        long_name: "One True Flag",
        station: null,
        icon: "Masters of Ceremony/One True Flag.svg",
        warbond: "masters_of_ceremony",
        active: false,
        backpack: false,
        support_weapon: true,
    },

    // --- Python Commandos ---
    defoliation_tool: {
        short_name: "Defoliation Tool",
        long_name: "Defoliation Tool",
        station: null,
        icon: "Python Commandos/Defoliation Tool.svg",
        warbond: "python_commandos",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    guard_dog_hot_dog: {
        short_name: "Guard Dog Hot Dog",
        long_name: "Guard Dog Hot Dog",
        station: null,
        icon: "Python Commandos/Guard Dog Hot Dog.svg",
        warbond: "python_commandos",
        active: false,
        backpack: true,
        support_weapon: false,
    },
    maxigun: {
        short_name: "Maxigun",
        long_name: "Maxigun",
        station: null,
        icon: "Python Commandos/Maxigun.svg",
        warbond: "python_commandos",
        active: false,
        backpack: true,
        support_weapon: true,
    },

    // --- Redacted Regiment ---
    c4_pack: {
        short_name: "C4 Pack",
        long_name: "C4 Pack",
        station: null,
        icon: "Redacted Regiment/C4 Pack.svg",
        warbond: "redacted_regiment",
        active: false,
        backpack: true,
        support_weapon: false,
    },

    // --- Servants of Freedom ---
    hellbomb_portable: {
        short_name: "Hellbomb Portable",
        long_name: "Hellbomb Portable",
        station: null,
        icon: "Servants of Freedom/Hellbomb Portable.svg",
        warbond: "servants_of_freedom",
        active: false,
        backpack: true,
        support_weapon: false,
    },

    // --- Siege Breakers ---
    bastion_mk_xvi: {
        short_name: "Bastion MK XVI",
        long_name: "Bastion MK XVI",
        station: null,
        icon: "Siege Breakers/Bastion MK XVI.svg",
        warbond: "siege_breakers",
        active: false,
        backpack: false,
        support_weapon: false,
    },
    cqc_20: {
        short_name: "Breaching Hammer",
        long_name: "CQC-20 Breaching Hammer",
        station: null,
        icon: "Siege Breakers/CQC-20.svg",
        warbond: "siege_breakers",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    eat_411: {
        short_name: "Leveller",
        long_name: "EAT-411 Leveller",
        station: null,
        icon: "Siege Breakers/EAT-411.svg",
        warbond: "siege_breakers",
        active: false,
        backpack: false,
        support_weapon: true,
    },
    gl_28: {
        short_name: "Belt-fed Grenade Launcher",
        long_name: "GL-28 Belt-fed Grenade Launcher",
        station: null,
        icon: "Siege Breakers/GL-28.svg",
        warbond: "siege_breakers",
        active: false,
        backpack: true,
        support_weapon: true,
    },

    // --- Urban Legends ---
    anti_tank_emplacement: {
        short_name: "Anti-Tank Emplacement",
        long_name: "Anti-Tank Emplacement",
        station: null,
        icon: "Urban Legends/Anti-Tank Emplacement.svg",
        warbond: "urban_legends",
        active: false,
        backpack: false,
        support_weapon: false,
    },
    directional_shield: {
        short_name: "Directional Shield",
        long_name: "Directional Shield",
        station: null,
        icon: "Urban Legends/Directional Shield.svg",
        warbond: "urban_legends",
        active: false,
        backpack: false,
        support_weapon: false,
    },
    flame_sentry: {
        short_name: "Flame Sentry",
        long_name: "Flame Sentry",
        station: null,
        icon: "Urban Legends/Flame Sentry.svg",
        warbond: "urban_legends",
        active: false,
        backpack: false,
        support_weapon: false,
    },
};

export default STRATAGEMS;
